package com.bank.management.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Account entity representing bank accounts in the system.
 *
 * This entity manages bank account information with proper validation,
 * relationships, and business rules.
 *
 * @author Senior Java Full Stack Developer
 * @version 1.0.0
 * @since 2026
 */
@Entity
@Table(name = "accounts", indexes = {
    @Index(name = "idx_account_number", columnList = "account_number", unique = true),
    @Index(name = "idx_account_user_id", columnList = "user_id"),
    @Index(name = "idx_account_type", columnList = "account_type"),
    @Index(name = "idx_account_status", columnList = "status"),
    @Index(name = "idx_account_opened_date", columnList = "opened_date")
})
public class Account {

    /**
     * Unique identifier for the account.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Unique account number generated by the system.
     */
    @NotBlank(message = "Account number is required")
    @Size(min = 10, max = 20, message = "Account number must be between 10 and 20 characters")
    @Pattern(regexp = "^A\\d{9}$", message = "Account number must start with 'A' followed by 9 digits")
    @Column(name = "account_number", nullable = false, unique = true, length = 20)
    private String accountNumber;

    /**
     * The user who owns this account.
     */
    @NotNull(message = "User is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Type of the account.
     */
    @NotNull(message = "Account type is required")
    @Enumerated(EnumType.STRING)
    @Column(name = "account_type", nullable = false, length = 15)
    private AccountType accountType = AccountType.SAVINGS;

    /**
     * Current balance of the account.
     */
    @NotNull(message = "Balance is required")
    @DecimalMin(value = "0.00", message = "Balance cannot be negative")
    @Digits(integer = 15, fraction = 2, message = "Balance must have at most 15 integer digits and 2 decimal places")
    @Column(name = "balance", nullable = false, precision = 15, scale = 2)
    private BigDecimal balance = BigDecimal.ZERO;

    /**
     * Currency of the account.
     */
    @NotBlank(message = "Currency is required")
    @Size(min = 3, max = 3, message = "Currency code must be exactly 3 characters")
    @Pattern(regexp = "^[A-Z]{3}$", message = "Currency code must be uppercase letters only")
    @Column(name = "currency", nullable = false, length = 3)
    private String currency = "INR";

    /**
     * Current status of the account.
     */
    @NotNull(message = "Status is required")
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 10)
    private AccountStatus status = AccountStatus.ACTIVE;

    /**
     * Branch name where the account was opened.
     */
    @Size(max = 100, message = "Branch name must not exceed 100 characters")
    @Column(name = "branch_name", length = 100)
    private String branchName;

    /**
     * IFSC code of the branch.
     */
    @Size(max = 11, message = "IFSC code must not exceed 11 characters")
    @Pattern(regexp = "^[A-Z]{4}\\d{7}$", message = "IFSC code must be 4 uppercase letters followed by 7 digits")
    @Column(name = "ifsc_code", length = 11)
    private String ifscCode;

    /**
     * Date when the account was opened.
     */
    @NotNull(message = "Opened date is required")
    @PastOrPresent(message = "Opened date cannot be in the future")
    @Column(name = "opened_date", nullable = false)
    private LocalDate openedDate = LocalDate.now();

    /**
     * Date when the account was closed (if applicable).
     */
    @Column(name = "closed_date")
    private LocalDate closedDate;

    /**
     * Timestamp when the account was created.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the account was last updated.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Default constructor.
     */
    public Account() {
    }

    /**
     * Constructor with essential fields.
     *
     * @param accountNumber the account number
     * @param user the account owner
     * @param accountType the account type
     * @param balance the initial balance
     */
    public Account(String accountNumber, User user, AccountType accountType, BigDecimal balance) {
        this.accountNumber = accountNumber;
        this.user = user;
        this.accountType = accountType;
        this.balance = balance;
    }

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public AccountType getAccountType() {
        return accountType;
    }

    public void setAccountType(AccountType accountType) {
        this.accountType = accountType;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public AccountStatus getStatus() {
        return status;
    }

    public void setStatus(AccountStatus status) {
        this.status = status;
    }

    public String getBranchName() {
        return branchName;
    }

    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    public String getIfscCode() {
        return ifscCode;
    }

    public void setIfscCode(String ifscCode) {
        this.ifscCode = ifscCode;
    }

    public LocalDate getOpenedDate() {
        return openedDate;
    }

    public void setOpenedDate(LocalDate openedDate) {
        this.openedDate = openedDate;
    }

    public LocalDate getClosedDate() {
        return closedDate;
    }

    public void setClosedDate(LocalDate closedDate) {
        this.closedDate = closedDate;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Checks if the account is active.
     *
     * @return true if account is active
     */
    public boolean isActive() {
        return status == AccountStatus.ACTIVE;
    }

    /**
     * Checks if the account is blocked.
     *
     * @return true if account is blocked
     */
    public boolean isBlocked() {
        return status == AccountStatus.BLOCKED;
    }

    /**
     * Checks if the account is closed.
     *
     * @return true if account is closed
     */
    public boolean isClosed() {
        return status == AccountStatus.CLOSED;
    }

    /**
     * Credits the specified amount to the account.
     *
     * @param amount the amount to credit
     */
    public void credit(BigDecimal amount) {
        if (amount.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Credit amount must be positive");
        }
        this.balance = this.balance.add(amount);
    }

    /**
     * Debits the specified amount from the account.
     *
     * @param amount the amount to debit
     */
    public void debit(BigDecimal amount) {
        if (amount.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Debit amount must be positive");
        }
        if (this.balance.compareTo(amount) < 0) {
            throw new IllegalArgumentException("Insufficient balance");
        }
        this.balance = this.balance.subtract(amount);
    }

    /**
     * Checks if the account has sufficient balance for a transaction.
     *
     * @param amount the amount to check
     * @return true if sufficient balance
     */
    public boolean hasSufficientBalance(BigDecimal amount) {
        return this.balance.compareTo(amount) >= 0;
    }

    /**
     * Gets the account holder's full name.
     *
     * @return the account holder's full name
     */
    public String getAccountHolderName() {
        return user != null ? user.getFullName() : null;
    }

    /**
     * Account type enumeration.
     */
    public enum AccountType {
        SAVINGS,
        CURRENT,
        FIXED_DEPOSIT
    }

    /**
     * Account status enumeration.
     */
    public enum AccountStatus {
        ACTIVE,
        BLOCKED,
        CLOSED
    }

    @Override
    public String toString() {
        return "Account{" +
                "id=" + id +
                ", accountNumber='" + accountNumber + '\'' +
                ", accountType=" + accountType +
                ", balance=" + balance +
                ", currency='" + currency + '\'' +
                ", status=" + status +
                ", openedDate=" + openedDate +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Account)) return false;
        Account account = (Account) o;
        return id != null && id.equals(account.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}